import { getRecommendation } from "@/app/lib/robin";
import type { Profile } from "@/app/lib/personas";

// Permissive CORS so the browser extension (and any deployed front-end) can call
// this endpoint. Lock the origin down for production/enterprise.
const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

export function OPTIONS() {
  return new Response(null, { status: 204, headers: CORS });
}

// Robin's recommendation endpoint. Takes a contributor profile, returns ranked
// recommendations generated by a live model (with a curated fallback).
export async function POST(request: Request) {
  let body: Partial<Profile & { targetRepo: string }>;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: "invalid JSON" }, { status: 400, headers: CORS });
  }

  const profile = {
    languages: Array.isArray(body.languages) ? body.languages : [],
    yearsExperience:
      typeof body.yearsExperience === "number" ? body.yearsExperience : 0,
    interests: Array.isArray(body.interests) ? body.interests : [],
    hoursPerWeek:
      typeof body.hoursPerWeek === "number" ? body.hoursPerWeek : 5,
    goals: typeof body.goals === "string" ? body.goals : "",
    targetRepo:
      typeof body.targetRepo === "string" && body.targetRepo
        ? body.targetRepo
        : "bitcoin/bitcoin",
  };

  const { response, source } = await getRecommendation(profile);
  return Response.json({ ...response, _source: source }, { headers: CORS });
}
