import { cookies } from "next/headers";
import { getRecommendation } from "@/app/lib/robin";
import type { Profile } from "@/app/lib/personas";
import { COOKIE_SUMMARY, decodeSummary } from "@/app/lib/githubOAuth";
import { corsHeaders } from "@/app/lib/cors";

// Reasoning models (e.g. Opus 4.8) take ~25-35s. Vercel kills serverless
// functions early by default — give this route room so it isn't truncated.
export const maxDuration = 60;

export function OPTIONS(request: Request) {
  return new Response(null, { status: 204, headers: corsHeaders(request) });
}

// Robin's recommendation endpoint. Takes a contributor profile, returns ranked
// recommendations generated by a live model (with a curated fallback).
export async function POST(request: Request) {
  const CORS = corsHeaders(request);
  let body: Partial<Profile & { targetRepo: string }>;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: "invalid JSON" }, { status: 400, headers: CORS });
  }

  const profile = {
    languages: Array.isArray(body.languages) ? body.languages : [],
    yearsExperience:
      typeof body.yearsExperience === "number" ? body.yearsExperience : 0,
    interests: Array.isArray(body.interests) ? body.interests : [],
    hoursPerWeek:
      typeof body.hoursPerWeek === "number" ? body.hoursPerWeek : 5,
    goals: typeof body.goals === "string" ? body.goals : "",
    targetRepo:
      typeof body.targetRepo === "string" && body.targetRepo
        ? body.targetRepo
        : "bitcoin/bitcoin",
  };

  // If the contributor connected GitHub, fold their derived skill summary in.
  const cookieStore = await cookies();
  const github = decodeSummary(cookieStore.get(COOKIE_SUMMARY)?.value);

  const { response, source } = await getRecommendation(profile, github);
  return Response.json({ ...response, _source: source }, { headers: CORS });
}
